# Generated by Django 6.0.6 on 2026-07-18 12:23

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=django_fsm.FSMField(choices=[('MOD', 'На проверке'), ('APR', 'Одобрено'), ('REG', 'Отклонено')], default='MOD', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
