# Generated by Django 6.0.6 on 2026-07-30 12:32

import django.db.models.deletion
import models_app.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pending_photo',
            field=models.ImageField(blank=True, null=True, upload_to=models_app.utils.upload.uploaded_file_path, verbose_name='Новая версия (на модерации)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='models_app.comment', verbose_name='Родитель'),
        ),
    ]
