# Generated by Django 6.0.8 on 2026-08-11 15:46

import models_app.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_photo_pending_photo_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pending_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='archive_photo',
            field=models.ImageField(blank=True, null=True, upload_to=models_app.utils.upload.uploaded_file_path, verbose_name='Старая фотка(Архив)'),
        ),
    ]
